fix: commented out unused nav items
project-ascend-io/intracom-06-2024 pull request #12
Opened 2024-09-20 01:49 UTC by diakymenko

## Ticket

ID: PAP-190
Link:
https://project-ascend-io.atlassian.net/browse/PAP-190
## Problem
"Messages" and "Channels" options in the sidebar should be commented out, and the "New Chat" button should be updated by removing its redirect action until this functionality is fully implemented

## Solution
commented out code responsible for displaying "Messages" and "Channels". Removed redirect from the "New Chat" button.

## Type of change
fix

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
tested for USER/ADMIN user types

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

## Checklist:

- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

<img width="791" alt="Screenshot 2024-09-19 at 6 34 25 PM" src="https://github.com/user-attachments/assets/56ec4b40-1aff-46ac-8215-1451a20a171a">

2024-09-20 20:47 UTC, bobbygrdn approved these changes, later dismissed
Great work on this! It's a clean solution with comments to pass on to the next developer who works on it.

2024-09-23 15:32 UTC, Amenu-sh commented
Well done Daria: 
Minor thing, the Link with the user profile avatar is navigating to an unknown space too. We'll be able to comment on it on our way.   
<Link to="/profile">

2024-09-23 15:40 UTC, Amenu-sh requested changes

2024-09-23 15:40 UTC, Amenu-sh commented on src/Components/nav-bar/nav-bar.tsx
>          <Link to="/profile">
We can comment-out this for now.

2024-09-23 16:51 UTC, diakymenko commented on src/Components/nav-bar/nav-bar.tsx
>          <Link to="/profile">
Thanks, Amenu. Should be fixed now.

2024-09-24 14:14 UTC, Amenu-sh approved these changes

2024-09-24 20:09 UTC, merged