Add electron register protocol handler
project-ascend-io/intracom-06-2024 pull request #15
Opened 2024-10-08 14:05 UTC by Amenu-sh

## Ticket

ID:
Link: https://project-ascend-io.atlassian.net/browse/PAP-224

## Problem

Users were unable to launch the downloaded app from the browser.

## Solution

Implemented a fix allowing users to open the downloaded app directly from the browser.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Tested locally in a browser environment.

## Checklist:

- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2024-10-19 22:05 UTC, oestrada1001 requested changes
Great job on adding the custom protocol!

One small request: it looks like two useful comments were accidentally removed, and two new ones were added. Could you please restore the deleted comments and remove any unnecessary or redundant ones to keep the code clean and concise?

Thanks for the great work!

2024-10-19 22:05 UTC, oestrada1001 commented on src/index.ts
> -// explicitly with Cmd + Q.
Please leave these comment in as they are useful and explain the `why?` something is happening.
The best practice for commenting is answering the `why?` something is needed rather than the `what?`.  A good example of the comments to remove are the ChatGPT comments as they are usually explaining the `what?`.

2024-10-19 22:05 UTC, oestrada1001 commented on src/index.ts
> -  // dock icon is clicked and there are no other windows open.
Leave this comment as well as its answering the `why?` question

2024-10-19 22:05 UTC, oestrada1001 commented on src/index.ts
> +  // On macOS, you can force protocol re-registration with:
This is a useful comment.

2024-10-19 22:05 UTC, oestrada1001 commented on src/index.ts
> +          headers: { "Content-Type": "application/octet-stream" }, // Adjust MIME type as needed
This is a useful comment as well.

2024-10-27 17:07 UTC, oestrada1001 commented
@Amenu-sh Just a heads up, I was going to approve the branch but noticed that the branch has conflicts that need to be resolved. Please merge the main branch into this branch, resolve the conflicts, then its ready for review before it can be merged.

2024-11-05 17:44 UTC, oestrada1001 commented on src/index.ts
> +  app.on("ready", async () => {
`app.whenReady` is the same as `app.on('ready'`, you should be able to remove the `app.on('ready', ()=> {});` wrapper on the following code:
```
const reactDevToolsPath = path.join(
      __dirname,
      "..",
      "..",
      "src",
      "assets",
      "tools",
      "reactDevTools",
    );
    try {
      await session.defaultSession.loadExtension(reactDevToolsPath);
      console.log("Added Extension: React Developer Tools");
      createWindow();
    } catch (err) {
      console.log("An error occurred: ", err);
      createWindow();
    }
```
and just put the code directly in `app.whenReady`.

2024-11-05 17:54 UTC, oestrada1001 requested changes
Thanks for adding the 'ignorePatterns' in the .eslintrc.json file. One minor improvement, theres two `app.on('ready')` on this file. We can remove the nested `app.on('ready')` wrapper and place its nested code in the other existing `app.on('ready')`.

2024-11-05 18:58 UTC, Amenu-sh reviewed
done

2024-11-05 21:30 UTC, oestrada1001 requested changes
Thank you for the rapid change Amenu. I tested the electron applications and although the application works, the ReactDevTools aren't working.

Please take a look at the plugin: https://chromewebstore.google.com/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi?hl=en

There should be two tabs in the chrome dev tools in our electron application like the screenshot in the plugin homepage(link above).

You'll have to make sure you have the plugin installed in our browser to be able to test it.

2024-11-06 04:02 UTC, oestrada1001 approved these changes
Great job @Amenu-sh ! This works perfectly and is a clean solution. Approved.

2024-11-06 04:04 UTC, merged